name: Test code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    run-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Install and setup Flutter version
        uses: subsito/flutter-action@v1.4.0
        with:
          flutter-version: '2.8.1'
      - name: Get packages
        run: flutter pub get
      - name: Test code
        run: flutter test